[package]
name = "truthoracle"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.9.2"
openzeppelin = "0.20.0"
pragma_lib = { git = "https://github.com/astraly-labs/pragma-lib", tag = "2.9.1" }
snforge_std = "0.35.0"

[[target.starknet-contract]]
# Enable Sierra codegen.
sierra = true
casm = true
